version: '3'
services:
  rstudio:
    image: rnotebook
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../container/local_test/test_dir:/opt/ml
      - ../container/algorithm:/opt/program
      - ..:/opt/volume
      - ~/.aws:/root/.aws
    environment:
      - USER
    working_dir: "/opt/volume"